GET http://localhost/api/replies/ HTTP/1.1
content-type: application/json

###
POST http://localhost/api/replies/ HTTP/1.1
content-type: application/json

{
    "topic_id": 1,
    "post_body": "post body test as a reply",
    "user_id": 4
}

###
PUT http://localhost/api/replies/24 HTTP/1.1
content-type: application/json

{
    "post_body": "post body test7"
}

###
DELETE  http://localhost/api/replies/24 HTTP/1.1
content-type: application/json