GET http://localhost/api/replies/ HTTP/1.1
content-type: application/json

###
POST http://localhost/api/replies/ HTTP/1.1
content-type: application/json

{
    "topic_id": 1,
    "post_body": "post body test as reply 1",
    "user_id": 1
}

###
PUT http://localhost/api/replies/24 HTTP/1.1
content-type: application/json

{
    "post_body": "post body reply 1 edit 1"
}

###
DELETE  http://localhost/api/replies/24 HTTP/1.1
content-type: application/json