GET http://localhost/api/topics/ HTTP/1.1
content-type: application/json

###

POST http://localhost/api/topics/ HTTP/1.1
content-type: application/json

{
    "title": "username1",
    "post_body": "post body test",
    "user_id": 1,
    
}

###
// check for date updated update
PUT http://localhost/api/topics/1 HTTP/1.1
content-type: application/json

{
    "post_body": "post body test6",
    
}

###
DELETE  http://localhost/api/topics/6 HTTP/1.1
content-type: application/json