GET http://localhost:8000/api/users/ HTTP/1.1
content-type: application/json

###
POST http://localhost:8000/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "username13",
    "email": "username13@gmail.com"
}

###
PUT http://localhost:8000/api/users/3 HTTP/1.1
content-type: application/json

{
    "username": "username1",
    "email": "username@gmail.com"
}