GET http://localhost/api/users/ HTTP/1.1
content-type: application/json

###
POST http://localhost/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "username",
    "email": "username@gmail.com"
}

###
PUT http://localhost/api/users/3 HTTP/1.1
content-type: application/json

{
    "username": "username1",
    "email": "username1@gmail.com"
}