GET http://localhost:8000/api/watchers/ HTTP/1.1
content-type: application/json

###
//duplicate on add
POST http://localhost:8000/api/watchers/ HTTP/1.1
content-type: application/json

{
    "post_id": 5,
    "user_id": 3
}

###
DELETE  http://localhost:8000/api/watchers/6 HTTP/1.1
content-type: application/json