GET http://localhost/api/watchers/ HTTP/1.1
content-type: application/json

###
POST http://localhost/api/watchers/ HTTP/1.1
content-type: application/json

{
    "post_id": 5,
    "user_id": 3
}

###
PUT http://localhost/api/watchers/ HTTP/1.1
content-type: application/json

{
    "post_id": 5,
    "user_id": 3
}

###
DELETE  http://localhost/api/watchers/6 HTTP/1.1
content-type: application/json